/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module error_checker_14 (
    input [15:0] new_a,
    input [15:0] new_b,
    input [5:0] new_alufn,
    input clk,
    input rst,
    output reg [5:0] alufn,
    output reg [15:0] a,
    output reg [15:0] b
  );
  
  
  
  reg [5:0] M_stored_alufn_d, M_stored_alufn_q = 1'h0;
  reg [15:0] M_stored_a_d, M_stored_a_q = 1'h0;
  reg [15:0] M_stored_b_d, M_stored_b_q = 1'h0;
  
  always @* begin
    M_stored_a_d = M_stored_a_q;
    M_stored_alufn_d = M_stored_alufn_q;
    M_stored_b_d = M_stored_b_q;
    
    M_stored_a_d = new_a;
    M_stored_b_d = new_b;
    M_stored_alufn_d = new_alufn;
    a = M_stored_a_q;
    b = M_stored_b_q;
    alufn = M_stored_alufn_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_stored_alufn_q <= 1'h0;
      M_stored_a_q <= 1'h0;
      M_stored_b_q <= 1'h0;
    end else begin
      M_stored_alufn_q <= M_stored_alufn_d;
      M_stored_a_q <= M_stored_a_d;
      M_stored_b_q <= M_stored_b_d;
    end
  end
  
endmodule
