/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_18 (
    input [7:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      8'h00: begin
        segs = 7'h3f;
      end
      8'h01: begin
        segs = 7'h06;
      end
      8'h02: begin
        segs = 7'h5b;
      end
      8'h03: begin
        segs = 7'h4f;
      end
      8'h04: begin
        segs = 7'h66;
      end
      8'h05: begin
        segs = 7'h6d;
      end
      8'h06: begin
        segs = 7'h7d;
      end
      8'h07: begin
        segs = 7'h07;
      end
      8'h08: begin
        segs = 7'h7f;
      end
      8'h09: begin
        segs = 7'h67;
      end
      8'h0a: begin
        segs = 7'h77;
      end
      8'h0b: begin
        segs = 7'h7c;
      end
      8'h0c: begin
        segs = 7'h39;
      end
      8'h0d: begin
        segs = 7'h6d;
      end
      8'h0e: begin
        segs = 7'h79;
      end
      8'h0f: begin
        segs = 7'h33;
      end
      8'h10: begin
        segs = 7'h00;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
