/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    output reg [2:0] customout,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [(3'h4+0)-1:0] M_buttoncond_out;
  reg [(3'h4+0)-1:0] M_buttoncond_in;
  
  genvar GEN_buttoncond0;
  generate
  for (GEN_buttoncond0=0;GEN_buttoncond0<3'h4;GEN_buttoncond0=GEN_buttoncond0+1) begin: buttoncond_gen_0
    button_conditioner_2 buttoncond (
      .clk(clk),
      .in(M_buttoncond_in[GEN_buttoncond0*(1)+(1)-1-:(1)]),
      .out(M_buttoncond_out[GEN_buttoncond0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  wire [(3'h4+0)-1:0] M_buttondetector_out;
  reg [(3'h4+0)-1:0] M_buttondetector_in;
  
  genvar GEN_buttondetector0;
  generate
  for (GEN_buttondetector0=0;GEN_buttondetector0<3'h4;GEN_buttondetector0=GEN_buttondetector0+1) begin: buttondetector_gen_0
    edge_detector_3 buttondetector (
      .clk(clk),
      .in(M_buttondetector_in[GEN_buttondetector0*(1)+(1)-1-:(1)]),
      .out(M_buttondetector_out[GEN_buttondetector0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  wire [24-1:0] M_alu_obj_led;
  wire [8-1:0] M_alu_obj_seg_out;
  wire [4-1:0] M_alu_obj_sel_out;
  reg [24-1:0] M_alu_obj_dip_input;
  reg [5-1:0] M_alu_obj_btn_input;
  alu_4 alu_obj (
    .clk(clk),
    .rst(rst),
    .dip_input(M_alu_obj_dip_input),
    .btn_input(M_alu_obj_btn_input),
    .led(M_alu_obj_led),
    .seg_out(M_alu_obj_seg_out),
    .sel_out(M_alu_obj_sel_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    customout = 3'h0;
    M_buttoncond_in[0+0-:1] = io_button[0+0-:1];
    M_buttondetector_in[0+0-:1] = M_buttoncond_out[0+0-:1];
    M_buttoncond_in[1+0-:1] = io_button[1+0-:1];
    M_buttondetector_in[1+0-:1] = M_buttoncond_out[1+0-:1];
    M_buttoncond_in[2+0-:1] = io_button[2+0-:1];
    M_buttondetector_in[2+0-:1] = M_buttoncond_out[2+0-:1];
    M_buttoncond_in[3+0-:1] = io_button[3+0-:1];
    M_buttondetector_in[3+0-:1] = M_buttoncond_out[3+0-:1];
    M_alu_obj_btn_input = M_buttondetector_out;
    M_alu_obj_dip_input = io_dip;
    io_seg = M_alu_obj_seg_out;
    io_sel = M_alu_obj_sel_out;
    io_led = M_alu_obj_led;
  end
endmodule
